### ISSUE TITLE
Meeting Protocol: Network mesh + VPN 

### ISSUE THREAD

**Issue by Chappie11** [tcfev/task-force-nika#14]
# Network mesh + VPN
Presents were:
@c379abe9eb21be7e5c3d292edaf50a6b @Chappie11 @armantorkzaban @86801e0e759a93d2995e988677251f7f

## Topics
* Network accessibility for Iran

## Actionable Tasks (topic, plan, deadline)
* [ ] Follow up meeting with 2702cc90e455a324f54c0ce7166dfca8 - 1 day
* [ ] Q: Who is going to take the role of managing this initiative? 

## Decision Making
* We have not made any key decisions yet, because we're meeting a second team with potentials to merge our efforts. In order to decide on the management of the team, a more solid and detailed plan is required so we can involve more experts. 
We presented the following diagram:
![img](https://raw.githubusercontent.com/tcfev/task-force-nika/main/assets/Iran-network-accessibility-diagram.png)

**Comment by jinaamini** [comment]
should this move to assets?
