### ISSUE TITLE
Introduce the discord channel we use to chat

### ISSUE THREAD

**Issue by armantorkzaban** [tcfev/task-force-nika#6]
We need to tell people where we mostly chat and let them join us there. 

Qs and concerns:
Should we remain on the same Discord WeAreMahsaAmini?
I would suggest yes, this way we reduce parallel efforts.
Once they become unstable we can move on to Session or another Discord server run by the TCF. WDYT?

**Comment by jinaamini** [comment]
I Agree with you. For now we can use a channel called task-force-nika in WeAreMahsaAmini.

**Comment by jinaamini** [comment]
On second thought, to mobilize this task force as soon as possible it might be better to start our own discord server ASAP

**Comment by armantorkzaban** [comment]
We need your input @Chappie11 @irannewswatch @Jiwe-Mobarez

Deadline: 12 hours.

**Comment by Jiwe-Mobarez** [comment]
i think WeAreMahsaAmini is fine for now.

**Comment by Chappie11** [comment]
I think we're good for now!

**Comment by jinaamini** [comment]
The majority agreed with using WeAreMahsaAmini channel.
